version: "3.9"
services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    environment:
      - SESSION_NAME=/app/sessions/airraidalert
